### ISSUE TITLE
个别情况下回导致创建网卡失败，更换IP后就后正常

### ISSUE THREAD

**Issue by phgors** [net-byte/vtun#31]
PS C:\Downloads> .\vtun.exe -l :3000 -s 192.168.117.130:3001 -k 123456    -c 172.16.0.10/24  -p ws
2022/08/17 03:27:22
_
__ __ | |_   _  _   _ _
\ V / |  _| | || | | ' \
 \_/   \__|  \_,_| |_||_|

A simple VPN written in Go. https://github.com/net-byte/vtun
2022/08/17 03:27:22 vtun version:v1.6.3
2022/08/17 03:27:22 vtun starting...
2022/08/17 03:27:22 initialized config:&{DeviceName: LocalAddr::3000 ServerAddr:192.168.117.130:3001 IntranetServerIP:172.16.0.1 IntranetServerIPv6:fced:9999::1 DNSServerIP:8.8.8.8 CIDR:172.16.0.10/24 CIDRv6:fced:9999::9999/64 Key:123456 Protocol:ws WebSocketPath:/freedom ServerMode:false GlobalMode:false Obfs:false Compress:false MTU:1500 Timeout:30 LocalGateway: TLSCertificateFilePath:./certs/server.pem TLSCertificateKeyFilePath:./certs/server.key TLSSni: TLSInsecureSkipVerify:false}
2022/08/17 03:27:22 vtun websocket client started on :3000
2022/08/17 03:27:22 Using existing driver 0.14
2022/08/17 03:27:22 Creating adapter
panic: The object already exists.

goroutine 8 [running]:
github.com/net-byte/water.openDev({0x1, {{0x6d0015, 0x4}, {0xc00001e130, 0xe}}})
        /home/alex/go/pkg/mod/github.com/net-byte/water@v0.0.4/syscalls_windows.go:48 +0x1ee
github.com/net-byte/water.New({0x1, {{0x6d0015, 0x4}, {0xc00001e130, 0xe}}})
        /home/alex/go/pkg/mod/github.com/net-byte/water@v0.0.4/if.go:61 +0x1ff
github.com/net-byte/vtun/tun.CreateTun({{0x0, 0x0}, {0xc00001e0b0, 0x5}, {0xc0000200f0, 0x14}, {0x6d457d, 0xa}, {0x6d60ca, 0xc}, ...})
        /home/alex/Work/projects/vtun/tun/tun.go:27 +0xff
github.com/net-byte/vtun/ws.StartClient({{0x0, 0x0}, {0xc00001e0b0, 0x5}, {0xc0000200f0, 0x14}, {0x6d457d, 0xa}, {0x6d60ca, 0xc}, ...})
        /home/alex/Work/projects/vtun/ws/wsclient.go:21 +0xa5
github.com/net-byte/vtun/app.(*Vtun).StartApp(0x0?)
        /home/alex/Work/projects/vtun/app/app.go:71 +0x27c
created by main.main
        /home/alex/Work/projects/vtun/main.go:41 +0x84e

**Comment by phgors** [comment]
<img width="1063" alt="1660678095233" src="https://user-images.githubusercontent.com/102591402/184966746-53b2ef62-d110-488d-b6dd-7d13d9841e7e.png">

**Comment by phgors** [comment]
问题找到了，是进程异常退出导致的IP设置没被清理掉。
<img width="544" alt="1660679686632" src="https://user-images.githubusercontent.com/102591402/184972853-e2b24c0f-8366-4147-8667-303982125726.png">

### 清理掉就可以了
`netsh interface ipv4 delete address "以太网" 172.16.0.10`
